version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appxpay_admin
    restart: unless-stopped
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=database-1.c1a42usmelhz.us-east-2.rds.amazonaws.com
      - DB_PORT=3306
      - DB_DATABASE=database-1
      - DB_USERNAME=admin
      - DB_PASSWORD=AppxPaySecure123!
    volumes:
      - ./appxpay-merchant:/var/www/html/appxpay-merchant   # Ensure this path is correctly mapped to your app
    ports:
      - "8080:80"   # Map Nginx's port 80 to host's port 8080
    networks:
      - appxpay-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: database-1
      MYSQL_USER: admin
      MYSQL_PASSWORD: AppxPaySecure123!
      MYSQL_ROOT_PASSWORD: root_password123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appxpay-network

networks:
  appxpay-network:
    driver: bridge

volumes:
  db_data:
